apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      containers:
        - name: enrollment-service
          image: us-central1-docker.pkg.dev/cloud-assignment-2-ahmedafzal/container-assignment-repo/enrollment:latest
          ports:
            - containerPort: 8080
          env:
            - name: CLOUD_SQL_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: CLOUD_SQL_CONNECTION_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASS
            - name: STUDENT_SERVICE_URL
              value: "http://student-service"
            - name: COURSE_SERVICE_URL
              value: "http://course-service"
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
spec:
  selector:
    app: enrollment-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
