apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: us-central1-docker.pkg.dev/cloud-assignment-2-ahmedafzal/container-assignment-repo/student:latest
          ports:
            - containerPort: 8080
          env:
            - name: CLOUD_SQL_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: CLOUD_SQL_CONNECTION_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
